openapi: 3.0.0
x-stoplight:
  id: px3r4cgrcgqyv
info:
  title: weather_api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /previsions:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prevision'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: get-Prevision
      x-stoplight:
        id: cmc4804pxmtfd
    parameters: []
  '/previsions/{city}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prevision'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: get-prevision-city
      x-stoplight:
        id: 7pgy3huysrmlx
      parameters:
        - schema:
            type: string
          in: query
          name: 'date '
    parameters:
      - schema:
          type: string
        name: city
        in: path
        required: true
  /citys:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: get-citys
      x-stoplight:
        id: 0bq57pumthxox
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
    put:
      summary: ''
      operationId: '/{id}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
      x-stoplight:
        id: sttss5skd315q
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
    post:
      summary: ''
      operationId: '/{id}'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
      x-stoplight:
        id: ji2jxjew0w5xw
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
    delete:
      summary: ''
      operationId: '/{id}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
      x-stoplight:
        id: vp0641zqrbm83
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
  '/citys/{city}':
    parameters:
      - schema:
          type: string
        name: city
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
      operationId: get-citys-city
      x-stoplight:
        id: hujmo2kn22ndk
components:
  schemas:
    Prevision:
      title: Prevision
      x-stoplight:
        id: t1v3i91qyetxm
      type: object
      properties:
        date:
          type: string
          x-stoplight:
            id: z9ihjhxw1q5or
          format: date
        temperature:
          type: integer
          x-stoplight:
            id: djdtt8xldi9ae
        city:
          type: string
          x-stoplight:
            id: pyav8aymdo8wm
        state:
          $ref: '#/components/schemas/Weither_state'
    Weither_state:
      title: Weither_state
      x-stoplight:
        id: l541ftz7zihc9
      enum:
        - ensoleillé
        - nuageux
        - pluvieux
        - 'venteux '
        - neigeux
    Error:
      title: Error
      x-stoplight:
        id: 9i1fjeetg5qo4
      type: object
      properties:
        code:
          type: string
          x-stoplight:
            id: vkaxhegpkv6ry
        description:
          type: string
          x-stoplight:
            id: 9bs4nfhot4j2i
    City:
      title: City
      x-stoplight:
        id: 45gxnkcxzdi8a
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: v50hhrck4j5pg
        nom_ville:
          type: string
          x-stoplight:
            id: fq7wscv8npzyw
        poste_code:
          type: integer
          x-stoplight:
            id: vk5cipkek9w9t
        country:
          type: string
          x-stoplight:
            id: xj43xni6branb
        region:
          type: string
          x-stoplight:
            id: cm4ayj1aaqf1j
