CREATE TABLE CITYS(ID VARCHAR(22),NAME VARCHAR(250),CODEPOSTAL VARCHAR(255),REGION VARCHAR(255), COUNTRY VARCHAR(255))
--     INSERT INTO CITYS (ID,NAME,CODEPOSTAL,REGION,COUNTRY)
--  VALUES('1','NIC','06200','COTE AZUR','FRANCE')

CREATE TABLE USERS(ID VARCHAR(22),LOGIN VARCHAR(250),PASSWORD VARCHAR(255))